<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentalyBooking.DataAccessLayer\RentalyBooking.DataAccessLayer.csproj" />
    <ProjectReference Include="..\RentalyBooking.DtoLayer\RentalyBooking.DtoLayer.csproj" />
    <ProjectReference Include="..\RentalyBooking.EntityLayer\RentalyBooking.EntityLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
    <Folder Include="ValidationRules\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
  </ItemGroup>

</Project>
