<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentalyBooking.DtoLayer\RentalyBooking.DtoLayer.csproj" />
    <ProjectReference Include="..\RentalyBooking.EntityLayer\RentalyBooking.EntityLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
